### ISSUE TITLE
Unresponsive repl on firefox-naked

### ISSUE THREAD

**Issue by neshaug** [emezeske/lein-cljsbuild#187]
With 0.3.0 (0862e71), "lein trampoline cljsbuild repl-launch firefox-naked" at example-projects/advanced results in a unresponsive (non-working) repl.

Leiningen 2.0.0 on Java 1.7.0_13 Java HotSpot(TM) 64-Bit Server VM

**Comment by Julian** [comment]
For anyone else finding this, it was the first thing I found when googling this error message -- turns out to mean "run a webserver, not `open foo.html`" for me.

**Comment by xealits** [comment]
I get the same error while following the [clojurescript getting started guide](https://github.com/clojure/clojurescript/wiki/Quick-Start) with `firefox 48.0`, `java-7-openjdk-amd64` on Ubuntu 14.04 LTS. (If some of the scripts in the guide implicitly call leiningen, my version is `Leiningen 2.5.3 on Java 1.8.0_76 OpenJDK 64-Bit Server VM`.)


On `rlwrap java -cp cljs.jar:src clojure.main repl.clj`
I get `Waiting for browser to connect ...` but there is no prompt,
though the parentheses auto-completion works.
And there is no output for a `(+ 1 2)` command,
also the auto-build file `out/watch.log` is not created.

In `http://localhost:9000/` (the page of repl connection) I get these:

    17:42:22.267 log:Transport created: NativeMessagingTransport
    POST http://localhost:9000/    200 OK    52ms     repl?xp...s.txt"} (line 2272)
    17:42:22.592 log:Can't send. Channel not connected.
    17:42:22.598 log:Channel "hoDROU3WL1" connected
    17:42:22.602 log:Channel "hoDROU3WL1" connected
    GET https://apis.google.com/_/scs/apps-static/_/js/k=...RSTNEfOH1MlcNEtB3fzWuGFFYKeAB0g/cb=gapi.loaded_0     404 Not Found   66ms     fastbut...refresh (line 78)
    GET https://apis.google.com/_/scs/apps-static/_/js/k=...TcCPiyITMO_1IXcnPwnSNLz7GwI4vZA/cb=gapi.loaded_1     200 OK          42ms     fastbut...refresh (line 78)
    uncaught exception: Error requesting /_/scs/apps-static/_/js/k=oz.gapi.ru._EQg8N9EI7Q.O/m=googleapis_client,iframes_styles_bubble_internal,gapi_iframes_style_common,gapi_iframes_iframer/rt=j/sv=1/d=1/ed=1/am=IQ/rs=AItRSTNEfOH1MlcNEtB3fzWuGFFYKeAB0g/cb=gapi.loaded_0: Not Found
    Current location: https://apis.google.com/u/0/_/+1/fastbutton?usegapi=1&bsv=o&size=standard&count=true&hl=en&url=http%3A%2F%2Flocalhost%3A9000%2F&origin=http%3A%2F%2Flocalhost%3A9000&parent=http%3A%2F%2Flocalhost%3A9000&gsrc=3p&ic=1&jsh=m%3B%2F_%2Fscs%2Fapps-static%2F_%2Fjs%2Fk%3Doz.gapi.ru._EQg8N9EI7Q.O%2Fm%3D__features__%2Fam%3DIQ%2Frt%3Dj%2Fd%3D1%2Frs%3DAItRSTNEfOH1MlcNEtB3fzWuGFFYKeAB0g#_methods=onPlusOne%2C_ready%2C_close%2C_open%2C_resizeMe%2C_renderstart%2Concircled%2Cdrefresh%2Cerefresh

and in `index.html` (the served page):

    17:42:27.952 log:Transport created: NativeMessagingTransport
    Error: URI file:/robots.txt is invalid for field ppu                       repl?xp...s.txt"} (line 2441, col 677)
    ...in a&&!/^https?:\/\//.test(a[d]))throw Error("URI "+a[d]+" is invalid for field ...

When I open `http://localhost:9000` in Chromium the repl springs to action,
says `out/watch.log` is ready and shows prompt.
The repl log:

    $ rlwrap java -cp cljs.jar:src clojure.main repl.clj
    Compiling client js ...
    Waiting for browser to connect ...
    
    
    
    (+ 1 2)
    Watch compilation log available at: out/watch.log
    
    To quit, type: :cljs/quit
    cljs.user=> cljs.user=> 
    cljs.user=> 
    cljs.user=> (+ 5 3)
    8
    cljs.user=> 
    cljs.user=> 

-- and console of `localhost:9000` shows only 404 about favicon, reloading `index.html` still shows the error with `robots.txt is invalid for field ppu`. The `watch.log` is there, and auto-rebuild works.
