### ISSUE TITLE
Macros should be reloaded each time in auto mode

### ISSUE THREAD

**Issue by ckirkendall** [emezeske/lein-cljsbuild#199]
If a set of macros use state (sometimes needed for optimization)  this state is carried from one compile to next in auto mode.  This can cause issues where the app will compile the first time but any modification to any file other than the macro will cause invalid code.   

I am current running into this while trying to optimize enfocus' compile time templates.  I want to make sure that the text value of a compiled template is only ever written out once.  I was using a compile time cache that I would check to see if it had been written out already.  This caused issues in auto mode because the cache was not reinitialized between compiles.   I am not sure how to get around this with out reloading the macro namespace each time.

**Comment by cemerick** [comment]
This convo is pretty out of date w.r.t. how reloading works in cljsbuild now.
