### ISSUE TITLE
Compiled ClojureScript added to uberjar without using `:jar true`

### ISSUE THREAD

**Issue by xavi** [emezeske/lein-cljsbuild#213]
I'm using Leiningen 2.2.0 and lein-cljsbuild 0.3.2. Hooks are enabled (`:hooks [leiningen.cljsbuild]`) but there's no `:jar true` entry in any ClojureScript build, however the uberjar generated with `lein uberjar` still contains the compiled ClojureScript (checked with `jar tf my.jar`).

This happens independently of if ClojureScript files are in the same directory as Clojure (I tried with `/src`), or in a separate directory (ex. `/src-cljs`). Also, it may be worth to mention that in the former case, adding the `:jar true` to a build configuration resulted in...

> Uberjar aborting because jar failed: duplicate entry: noir_auth_app/i18n.clj

(noir_auth_app/i18n.clj is a file of the project being compiled)

**Comment by dustingetz** [comment]
I have a similar issue. `lein uberjar` is executing the first item listed in  `:cljsbuild :builds`. So my prod build has to come first. If I put my prod build last, I get the wrong cljs assets. cljs-build 1.0.5.

Here's the project.clj: https://gist.github.com/dustingetz/e0abd5b0120bca7b7a8e

**Comment by bostonaholic** [comment]
I'm having the same issue as @dustingetz. I have both `:dev` and `:prod` compilation targets that both produce `resources/public/js/main.js`. But since `:dev` comes first, it is the one that is chosen to be built with `lein uberjar`.

Id would be nice to have a way to tell `uberjar` (or `jar`) which `cljsbuild` target to use.

**Comment by lvh** [comment]
Since you can provide a list of targets, is it possible to just put prod first?
