### ISSUE TITLE
Allow to fail build when ClojureScript compiler emits warnings

### ISSUE THREAD

**Issue by jeluard** [emezeske/lein-cljsbuild#225]
When `lein cljsbuild once` generates WARNING (via the ClojureScript compiler) the build is considered successful (a green `Successfully compiled` is printed). The same applies to exception thrown (e.g. when a defn is malformed).

As you can easily miss those it would be nice to have some option to let the build fail and have some corresponding message printed.
An alternative would be to have something similar to `lein check` for ClojureScript.

This might require changes in ClojureScript compiler as those warnings are directly printed to the output stream there.

**Comment by sir-pinecone** [comment]
Has anyone made progress on this? I just got bit with a warning that slipped through into a production build and it broke the app for several customers.

**Comment by cemerick** [comment]
Yup, the hooks for this exist now in `:warning-handlers`.
