### ISSUE TITLE
is the :jar true option needed?

### ISSUE THREAD

**Issue by magomimmo** [emezeske/lein-cljsbuild#258]
I'm really confused. 

In #256 and #257 has been said that the Leiningen `:source-paths` has to be the superset of the `:source-paths` of each `cljsbuild` build. 

To me this is a violation of the separation of concerns principle, because I would like to keep the CLJ codebase completely separated from the CLJS codebase. The fact that cljsbuild does not add the CLJS pathnames valued in the `:source-paths` to the `classpath` is just something that the developer should not think about. If it's needed by the compiler that addition should have be done by the cljsbuld itself, not by the developer. This requirements is also a violation of the DRY principle. Why should I write twice the same things? But this is just my humble opinion.

That said, the above requirement has also bad consequences on the `lein jar` command. If you launch the `lein cljsbuild sample` command to take a look at the annotated example, you'll read:

```bash
; If hooks are enabled, this flag determines whether files from these
        ; :source-paths are added to the JAR file created by "lein jar".
        :jar true
```  
So let's hook cljsbuild in the simple provided example, add the `"src-cljs"` to the Leiningen `:source-paths` and finally add the `:jar true` option to the only available build in the example. 

```clj
(defproject cljsbuild-example-simple "0.3.4"
  :description "A simple example of how to use lein-cljsbuild"
  :source-paths ["src-clj" "src-cljs"]
  :dependencies [[org.clojure/clojure "1.5.1"]
                 [org.clojure/clojurescript "0.0-1859"
                  :exclusions [org.apache.ant/ant]]
                 [compojure "1.1.6"]
                 [hiccup "1.0.4"]]
  :plugins [[lein-cljsbuild "0.3.4"]
            [lein-ring "0.8.7"]]

  :hooks [leiningen.cljsbuild]
  
  :cljsbuild {:builds [{:source-paths ["src-cljs"]
                        :jar true
                        :compiler {:output-to "resources/public/js/main.js"
                                   :optimizations :whitespace
                                   :pretty-print true}}]}
  :ring {:handler example.routes/app})
```

Not run the lein task to generate the jar package:

```bash
Giacomo-Cosenzas-iMac:simple mimmo$ lein do clean, compile, jarDeleting files generated by lein-cljsbuild.
Compiling ClojureScript.
Compiling "resources/public/js/main.js" from ["src-cljs"]...
Successfully compiled "resources/public/js/main.js" in 7.018413 seconds.
Compiling ClojureScript.
java.util.zip.ZipException: duplicate entry: example/hello.cljs
...
```

If you now remove the `:jar true` option, the jar is packaged. 

To me, if I'm not wrong somewhere as I hope, this is really a big issue. You can fine the above modified repo [here][1].

My personal opinion is to go for the automagic addition of the CLJS pathnames to the Leiningen `:source-paths`. It will solve in one shot the violation of the separation of concerns principle, the violation of the DRY principle, and any incidental complexity we should take care of because of the above violation. 

thas said, I hope to be wrong.

[1]: https://github.com/magomimmo/lein-cljsbuild/tree/automagic/example-projects/simple

**Comment by cemerick** [comment]
The `:jar` option should probably be avoided, along with Leiningen hooks. See #405.
