### ISSUE TITLE
Problems using repl-listen and Chrome

### ISSUE THREAD

**Issue by smiler** [emezeske/lein-cljsbuild#262]
Using a minimal project I can't get Chrome to connect correctly to the repl. Evaluating something simple like (+ 1 1) stalls the process. Visiting the same URL later using Firefox completes the evaluation. The behavior has been repeated by at least one person in the #clojure IRC channel. Produced this using Chrome 31.0.1650.39 beta. Tested source is available at https://gist.github.com/smiler/7316919.

**Comment by cemerick** [comment]
The CLJS REPL was completely rearchitected earlier this year, so this should not be a problem anymore.
