### ISSUE TITLE
Use SNAPSHOT plugin dependency to deliver up-to-date ClojureScript/cljsbuild compatibility info

### ISSUE THREAD

**Issue by cemerick** [emezeske/lein-cljsbuild#266]
ClojureScript, and specifically its compiler API, is very volatile, such that various versions of lein-cljsbuild are only compatible with certain ranges of ClojureScript builds.  However, because ClojureScript's release versioning isn't anything remotely semver, there's no way to determine (or even speculate about) compatibility based on its version number.  This means that a user has no way to know whether ClojureScript 0.0-XXXX will work correctly with lein-cljsbuild A.B.C short of trying the combination, and either looking for errors, or potentially discovering [incorrect compilation results](gh-253) long after changing dependencies.  This all means that, even if maven version ranges were acceptable within the Clojure community, lein-cljsbuild could not use them to declare upstream compatibility.

(This is even worse than most other dependency conflicts / compatibility problems, since even the most hipster of libraries will bump the "minor" version number [in semver parlance] when breakage and/or major features are introduced.  Because the only information in the ClojureScript version string is a monotonically-increasing commit number, it's effectively just dumb luck when a particular ClojureScript release works properly with a lein-cljsbuild release that wasn't "qualified" against it.  Also, the ClojureScript dependency is utilized by both build-time components [like cljsbuild] and delivers runtime APIs, so users understandably want to upgrade it independent of cljsbuild releases to benefit from improvements in the latter without waiting for cljsbuild maintainers to act.)

My current idea is to use a plugin-side SNAPSHOT dependency to deliver compatibility information as it becomes available.  So, when a new rev of ClojureScript is released, and problems are discovered/reported when using it with various lein-cljsbuild releases, that compatibility info can be updated via a new SNAPSHOT deployment, capping the ClojureScript releases can can be used with potentially many lein-cljsbuild releases.

The big downside of this is that that SNAPSHOT will provoke dependency resolution on every lein-cljsbuild run, though lein/aether defaults should ensure that that results in an actual network check only every 24 hours.  lein-cljsbuild is a plugin, and so this SNAPSHOT will not affect users' projects' dependencies at all.

If this causes unforeseen problems, then rolling it back will be straightforward.

**Comment by cprice404** [comment]
FWIW this tripped me up for a good while today because our CI system is set up to only use our internal Nexus server to get artifacts, and we mirror clojars *for releases*, but not SNAPSHOTs.  Will probably require special configuration of our Nexus server that we would definitely not do otherwise, because this is probably the only SNAPSHOT we'd ever be willing to tolerate coming into a build... :/

But obviously this has been working for 2 years and I don't necessarily have any better ideas.

**Comment by mneise** [comment]
@cprice404 As per #406, cljs-compat will be removed in the future, so the SNAPSHOT dependency should not be an issue anymore :wink:

**Comment by cprice404** [comment]
oh nice thanks for the heads up

**Comment by danielflower** [comment]
Before #406 gets released, has anyone been able to get lein-cljsbuild working with an internal nexus? It's just recently broken and we can't compile clojurescript anymore.

**Comment by danielcompton** [comment]
@danielflower wouldn't this be better for an internal nexus, as you wouldn't have any snapshots in your dependencies?

**Comment by danielflower** [comment]
Yes, it would, but it looks like it's going in as part of a big release with no release date that I'm aware of. Until then we can't use clojure script unless there is a workaround.

**Comment by mneise** [comment]
@danielflower Just released `1.1.3` which removes `cljs-compat`. Maybe you could give that a go :wink:

**Comment by danielflower** [comment]
That worked! Thanks so much.
