### ISSUE TITLE
reloading macros

### ISSUE THREAD

**Issue by txrev319** [emezeske/lein-cljsbuild#285]
I believe the following is a bug, though it could be just I'm doing something stupid.

This is the situation:

## case 1
* foo.cljs uses :require-macros [macros]
* macros.clj does not exist
* I run "lein cljsbuild auto" --> error
* I update macros.clj
* "lein cljsbuild auto" (exisitng process) --> still outputs errors

## case 2
* I restart "lein cljsbuild auto" (with macros.clj present from the start) --> all works fine

So it appears that "lein cljsbuild auto" is NOT reloading macros in *.clj files.

Is this consistent with existing lein cljsbuild behavior, or am I doing something retarded?

Thanks!

**Comment by cemerick** [comment]
Reloading was tweaked quite a bit by Bruce in 1.0.4 in conjunction with the development of figwheel, so this should be addressed now.
