### ISSUE TITLE
incremental compilation could recompile previous file with error, so it does not mask things

### ISSUE THREAD

**Issue by geraldodev** [emezeske/lein-cljsbuild#288]
Hi,

When in incremental compilation mode when you save a file with error it properly shows the message.
When you make changes on another file and save the message says it was properly compiled despite of the previous one with error.
cljsbuild could include  previous compiled files with errors in the process.

First issue here. Thanks for the project. It's awesome!

**Comment by cemerick** [comment]
Which errors are or are not reported is driven by the CLJS compiler, and not under cljsbuild's control.
