### ISSUE TITLE
Document :preamble

### ISSUE THREAD

**Issue by kendagriff** [emezeske/lein-cljsbuild#309]
I'm puzzled by the `:preamble` configuration option. It's not discussed in the _sample.project.clj_, or anywhere else I've found. I've needed it for `:advanced` compilation with `:externs`, however, I have no idea why. I've simply copied things I've seen in examples. This is probably my lack of familiarity with Google Closure showing through.

Any thoughts?

**Comment by mnn** [comment]
This is very confusing. I was expecting to be relative to build script, so `script_header.js` means `./script_header.js` from project root perspective. This really should be mentioned in documentation or in an error message, because it's really unclear where the files are being taken from.

**Comment by mneise** [comment]
@mnn Looks like there is a PR for this already: https://github.com/clojure/clojurescript-site/pull/144.
