### ISSUE TITLE
Missing `project`.version system property during compilation

### ISSUE THREAD

**Issue by jeluard** [emezeske/lein-cljsbuild#318]
The `project`.version system property set by leiningen is not set during ClojureScript compilation.
There's a `.version` property set though so it looks like the project name is omitted.

**Comment by danielcompton** [comment]
Running this now, `.version` is null in the System properties, and there doesn't seem to be a pom.properties at cljsbuild macro expansion time. Is there another way around this?

I'm using leiningen 2.5.0, and cljsbuild 1.0.5.

**Comment by cemerick** [comment]
The `pom.properties` is in `META-INF`, `(clojure.java.io/resource "META-INF/maven/group/artifact/pom.properties")`. More here: https://github.com/technomancy/leiningen/blob/master/doc/FAQ.md

**Comment by danielcompton** [comment]
Sorry I wasn't very clear in what I tried. I followed the FAQ instructions, but at the time when the ClojureScript macros are being compiled and I try to load the `pom.properties` file, `io/resource` returns `nil`. It seems like this is because the `pom.properties` file doesn't exist yet, as the same code works running from a Clojure REPL.

**Comment by cemerick** [comment]
It certainly used to? I can't say I've ever done this (looked for it during CLJS macroexpansion), but others apparently have. Perhaps this is a change since e.g. lein 2.4.2, which was in use just prior to this issue being closed.

**Comment by danielcompton** [comment]
Hmm, @jeluard could you offer any insight on this?

**Comment by jeluard** [comment]
I don't rely on this anymore but I was using a variation of:

```clojure
(defn read-properties
  [s]
  (let [p (Properties.)]
    (if-let [r (clojure.java.io/resource s)]
      (.load p (clojure.java.io/reader r)))
    (into {} p)))

(defmacro read-configuration
  []
  (read-properties "META-INF/maven/YOUR-GROUP/YOUR-PROJECT/pom.properties"))
```

It might not work anymore. I don't recommend it anyway, too flaky.

**Comment by danielcompton** [comment]
Hmm, it doesn't seem to work for the current project at build time, though it will happily get the `pom.properties` of other JARs. I think I'll investigate another solution, thanks for your help!
