### ISSUE TITLE
1.0.4 doesn't build after 'lein clean'

### ISSUE THREAD

**Issue by Gregg8** [emezeske/lein-cljsbuild#358]
*NOTE: Having targeted this issue for `cljsbuild`, it did occur to me that this is more likely a `leiningen` problem, however, I'm happy to place it here for starters as it should be affecting us cljsbuild users...*

The replacement of `lein cljsbuild clean` with `lein clean` in `1.0.4` behaves differently for our project.

Here are the relevant parts of the project.clj file:

```Clojure
:clean-targets    ^{:protect false} ["run/compiled/demo"]

:cljsbuild        {:builds [{:id "demo"
                             :source-paths   ["src"]
                             :compiler       {:output-to     "run/compiled/demo.js"
                                              :source-map    "run/compiled/demo.js.map"
                                              :output-dir    "run/compiled/demo"
                                              :optimizations :none
                                              :pretty-print  true}}}]}

:aliases          {"auto-demo"     ["do" "clean," "cljsbuild" "auto" "demo,"]}
```

In `1.0.3`, we could happily type `lein auto-demo`, the old files would be cleaned and the project built in the appropriate folder structure.

However, on upgrading to `1.0.4` (and adding the `:clean-targets` info), the `auto-demo` alias doesn't build after cleaning.

After arriving at this non-built state, editing a source file will trigger the build and I'm off and away.

Through experimentation, I believe the problem is due to the existence of the `:output-to` file (demo.js). If I remove this file before running `auto-demo`, the whole process works.

`1.0.3` previously DID delete this file during the clean process. This looks like the root of the problem here.

Tried running the commands individually, in case the alias was causing an issue. Same results.

The issue is confirmed on both Windows 8.1 and Ubuntu.

**Comment by Gregg8** [comment]
Perhaps I dumped too much of the `project.clj` file above so I have paired it back to make it simpler to digest (and stripped the other text back a bit too).

Also, my actual suggestion of crux of the problem comes about half way down so I have extracted it here:

    1.0.3 previously DID delete the file specified in :output-to during the clean process

So, if 1.0.4 could also clean this file then it would all behave as before. Open to other thoughts as well.

**Comment by cemerick** [comment]
cljsbuild no longer has any hand in the cleaning of compilation output; it's entirely up to `lein clean` now. I'd suggest changing your `:clean-targets` to `["run/compiled"]`, so that all cljsbuild output is removed by Leiningen.

**Comment by Gregg8** [comment]
Thanks for that, it did ultimately do the trick, so this issue now stands as a helper to others who experienced this difference in `clean` behaviour between `cljsbuld` and `lein`.

As a side note, my build for `figwheel` continued to work just fine, without having to specify the directory above.

Anyway, thanks again and case closed.
