### ISSUE TITLE
lein-cljsbuild 1.0.4 tries to reload data_readers.clj

### ISSUE THREAD

**Issue by tonsky** [emezeske/lein-cljsbuild#360]
Hi!

I see a regression after upgrading from 1.0.3 to 1.0.4.

**Problem:**

I have `data_readers.clj` on my project. With 1.0.3 everything builds just fine, but on 1.0.4 I get this when running `lein cljsbuild once`:

    [~/work/cljsbuild_data_readers] lein cljsbuild once
    Compiling ClojureScript.
    Reloading Clojure file "/data_readers.clj" failed.
    clojure.lang.Compiler$CompilerException: java.lang.RuntimeException: No such namespace: tonsky, compiling:(data_readers.clj:1:249)
                   Compiler.java:6464 clojure.lang.Compiler.analyze
                   Compiler.java:6406 clojure.lang.Compiler.analyze
                   Compiler.java:2980 clojure.lang.Compiler$MapExpr.parse
                   Compiler.java:6453 clojure.lang.Compiler.analyze
                   Compiler.java:6406 clojure.lang.Compiler.analyze
                   Compiler.java:5782 clojure.lang.Compiler$BodyExpr$Parser.parse
                   Compiler.java:5217 clojure.lang.Compiler$FnMethod.parse
                   Compiler.java:3846 clojure.lang.Compiler$FnExpr.parse
                   Compiler.java:6642 clojure.lang.Compiler.analyzeSeq
                   Compiler.java:6445 clojure.lang.Compiler.analyze
                   Compiler.java:6700 clojure.lang.Compiler.eval
                   Compiler.java:7130 clojure.lang.Compiler.load
                          RT.java:370 clojure.lang.RT.loadResourceScript
                          RT.java:361 clojure.lang.RT.loadResourceScript
                          RT.java:440 clojure.lang.RT.load
                          RT.java:411 clojure.lang.RT.load
                        core.clj:5641 clojure.core/load[fn]
                        core.clj:5640 clojure.core/load
                      RestFn.java:408 clojure.lang.RestFn.invoke
                     compiler.clj:128 cljsbuild.compiler/reload-clojure[fn]
                     compiler.clj:127 cljsbuild.compiler/reload-clojure
                     compiler.clj:175 cljsbuild.compiler/run-compiler
    form-init7611321090116486617.clj:1 user/eval3519[fn]
    form-init7611321090116486617.clj:1 user/eval3519[fn]
                      LazySeq.java:40 clojure.lang.LazySeq.sval
                      LazySeq.java:49 clojure.lang.LazySeq.seq
                          RT.java:484 clojure.lang.RT.seq
                         core.clj:133 clojure.core/seq
                        core.clj:2855 clojure.core/dorun
                        core.clj:2871 clojure.core/doall
    form-init7611321090116486617.clj:1 user/eval3519
                   Compiler.java:6703 clojure.lang.Compiler.eval
                   Compiler.java:6693 clojure.lang.Compiler.eval
                   Compiler.java:7130 clojure.lang.Compiler.load
                   Compiler.java:7086 clojure.lang.Compiler.loadFile
                         main.clj:274 clojure.main/load-script
                         main.clj:279 clojure.main/init-opt
                         main.clj:307 clojure.main/initialize
                         main.clj:342 clojure.main/null-opt
                         main.clj:420 clojure.main/main
                      RestFn.java:421 clojure.lang.RestFn.invoke
                         Var.java:383 clojure.lang.Var.invoke
                         AFn.java:156 clojure.lang.AFn.applyToHelper
                         Var.java:700 clojure.lang.Var.applyTo
                         main.java:37 clojure.main.main
    Caused by: java.lang.RuntimeException: No such namespace: tonsky
                        Util.java:221 clojure.lang.Util.runtimeException
                   Compiler.java:6910 clojure.lang.Compiler.resolveIn
    target/*
                   Compiler.java:6884 clojure.lang.Compiler.resolve
                   Compiler.java:6845 clojure.lang.Compiler.analyzeSymbol
                   Compiler.java:6427 clojure.lang.Compiler.analyze
    Compiling "release.js" from ["src"]...
    Successfully compiled "release.js" in 12.125 seconds.

**Steps to reproduce:**

    git clone https://github.com/tonsky/cljsbuild_data_readers.git
    cd cljsbuild_data_readers
    lein cljsbuild once

**Expected behavior:**

`data_readers.clj` should not be interpreted as clojure source file. Instead, it’s more of a EDN data file, there should be no `eval` over it.

Thanks!

Nikita.

**Comment by cemerick** [comment]
fixed on develop/1.x, will be merging to master and releasing shortly
