### ISSUE TITLE
Means of bypassing compilation

### ISSUE THREAD

**Issue by dchelimsky** [emezeske/lein-cljsbuild#363]
My workflow includes running a repl in one shell and `lein cljsbuild auto` in another. I'd like to bypass cljs compilation when starting up the repl to speed things up (right now I have to go through two compilation cycles to start a new session).

I've tried moving all of the lein-cljsbuild related declarations to a separate profile and running the repl with that, but I haven't gotten it to work for reasons I don't yet understand, but I think another solution would be to add a `:bypass`, or `:skip` option that I can include in a profile, e.g.

```clj
:dev-without-cljs {:cljsbuild {:bypass true}}
:dev [:dev-without-cljs
      {:cljsbuild {:builds ...... }}]
```

Then I should be able to run `lein with-profile dev-without-cljs repl` in one shell, `lein with-profile dev cljsbuild auto` in another and voila!

WDYT?

**Comment by benmoss** [comment]
Not sure I totally understand this, but it sounds like you're saying that running `lein repl` causes a compile? This isn't the default behavior, I think it must be something else in the project that is doing that.

**Comment by dchelimsky** [comment]
Entirely possible. I'll do some more research and see if I can pin it down. Feel free to close this or leave it open and I'll report back here if/when I have more to report.

**Comment by cemerick** [comment]
I agree with @benmoss, you must have hooks in place or something.

**Comment by dchelimsky** [comment]
Hey - yep - hooks. Works now, so closing.
