### ISSUE TITLE
js files not copied to output-dir

### ISSUE THREAD

**Issue by olivergeorge** [emezeske/lein-cljsbuild#365]
Just sanity checking this as it seems odd/annoying (but I could well be doing things wrong).  I've added a .js file to my chestnut based project.  In dev mode with {:optimizations :none} the js file is referenced but not copied to the :output-dir.

The output-to file looks like this...

```javascript
...
goog.addDependency("../cljsjs/development/react.inc.js", ['cljsjs.react'], []);
goog.addDependency("../om/dom.js", ['om.dom'], ['cljs.core', 'goog.object', 'cljsjs.react']);
goog.addDependency("../../../../../src/cljs/metcalf/geo.js", ['metcalf.geo'], []);
goog.addDependency("../clojure/set.js", ['clojure.set'], ['cljs.core']);
goog.addDependency("../sablono/util.js", ['sablono.util'], ['goog.Uri', 'cljs.core', 'clojure.set', 'clojure.string']);
goog.addDependency("../sablono/interpreter.js", ['sablono.interpreter'], ['sablono.util', 'cljs.core', 'goog.object', 'cljsjs.react', 'clojure.string']);
...
```

That's a pain because the .js file is not in my resources path to serve to the browser.

Curious to know if this is expected behaviour.  Perhaps it is convention to place .js files in the resources dir from the outset?

**Comment by tillda** [comment]
+1 I ran into this EXACT issue. It would be soo cool to be able to include cloSure .js files in cljs project. I also ran into the problem with /resources directory, since it is the only one that figwheel is able to serve files from. I used a dirty workaround to symlink src in resources/public.

**Comment by olivergeorge** [comment]
You might find this helpful tillda
https://github.com/clojure/clojurescript/wiki/Compiler-Options#libs

**Comment by tillda** [comment]
@olivergeorge I tried `:libs`, but the problem is that they stay in a different directory and the Closure Compiler dependencies are weird then. Like ../../../../../src/foo/bar.js. This means that some special routing in the development webserver is needed.

**Comment by cemerick** [comment]
lein-cljsbuild simply passes these options to the ClojureScript compiler. The best I can suggest is to refer to its documentation, and/or look for help troubleshooting issues on the CLJS mailing list.
