### ISSUE TITLE
Revert elimination of lein cljsbuild clean.

### ISSUE THREAD

**Issue by levand** [emezeske/lein-cljsbuild#376]
I would like to request that the decision to eliminate `lein cljsbuild clean` (from #297) be reconsidered.

Telling users to use `lein clean` is quite newbie-unfriendly. Most time, users will be not be compiling into `./target` - almost invariably, ClojureScript is compiled into `resources/public` or something similar. This immediately forces users into using the leiningen `:clean-targets` key, which is itself virtually undocumented, and not only that, but forces adding the arcane `^{:protect false}` metadata to get it to actually work.

This is nearly incomprehensible to someone trying to get started.

lein-cljsbuild actually does have some information about the real, specific output locations of emitted JavaScript files. Aside from unfortunate pathological cases like that in #297, it seems to me that we should use that information rather than making the user repeat themselves. And if people get in the habit of cargo-culting `^{:protect false} :clean-targets`, we're likely to see more mistakes in the vein of #297 anyway. 

Building to `./target` so things work by default isn't really a viable ClojureScript workflow.  Serving from `./target` is a (potential) security flaw, and requiring a separate step to copy the JS to somewhere it can be served from is inordinately cumbersome.

**Comment by cemerick** [comment]
I don't understand the impulse to write compilation output to a source directory. Goes against everything I've ever learned (often the hard way) about structuring projects and build processes.

Anyway, a restatement of the rationale for the change is @ https://github.com/cemerick/clojurescript.test/issues/97. `:protect false` isn't necessary if one isn't trying to clean out of well-known source directories; Leiningen has many flaws, but it's doing the right thing here (potentially doing ill _should_ require arcane bits).

Why is serving out of `target` a security issue, especially in a development scenario?

**Comment by Frozenlock** [comment]
The Reagent template uses the same method as described here.
Seems many people think the `:clean-targets` is the way to go, or don't know better.
Is there any example of a clojurescript project NOT doing it? 
(A project which is ultimately uberjared... not a simple library.)

https://github.com/reagent-project/reagent-template/blob/master/src/leiningen/new/reagent/project.clj#L37

**Comment by cemerick** [comment]
Doing an issue scrub; can't say my opinion has changed since my first comment. It sounds like @levand is working in a context where an app is being served out of a working directory outside of a dev scenario (maybe using .gitignores to avoid letting compilation artifacts into commits under `./resources`?), not something I'd want to make easier.
