### ISSUE TITLE
Compile crashes with newer clojurescript dependencies

### ISSUE THREAD

**Issue by auramo** [emezeske/lein-cljsbuild#384]
I get this error:

Unsupported binding form: :as, compiling:(cljs/closure.clj:1127:1)
Full stack: https://gist.github.com/auramo/aea73858ca3a000d44a6

When I try to compile anything with clojurescript dependencies from at least 0.0-2727 to 0.0-3126. If I choose the version 0.0-2197 which is mentioned in the README, compilation works.  Here is an example project.clj:

```
(defproject lein-cljsbuild-example "1.2.3"
  :plugins [[lein-cljsbuild "1.0.5"]]
  :dependencies [[org.clojure/clojurescript "0.0-3126"]]
  :cljsbuild {
    :builds [{
        :source-paths ["src"]
        :compiler {
          :output-to "out/init.js"
          :optimizations :whitespace
                   :pretty-print true}}]})
```

With the currently newest clojurescript depencency. The compilation fails with empty src directory, or with some core.clj there (the sources don't seem to matter, it fails even earlier).

**Comment by swannodette** [comment]
There's not enough information here. I generally build something non-trivial with ClojureScript and cljsbuild prior to releases. I just tested core.logic with 0.0-3126 using cljsbuild and didn't see anything like this. Make sure you don't have a AOT cached version of ClojureScript or anything like that in `target`.

**Comment by cichli** [comment]
Adding a dependency to `[org.clojure/clojure "1.6.0"]` or later will likely fix this. See the line notes on [this commit](https://github.com/clojure/clojurescript/commit/ab72c79f02a43670de63a0eea66c6baebc354e92).

**Comment by auramo** [comment]
@swannodette I created an example project here: https://github.com/auramo/lein-cljs-issue
You can just clone it and run lein cljsbuild once to repeat the issue. My lein version is 2.5.1.

**Comment by swannodette** [comment]
@auramo you need to specify a version of Clojure >= 1.6.0.

**Comment by auramo** [comment]
Explicit clojure dependency with version 1.6.0 helped. Thanks!

**Comment by wolverian** [comment]
Should the dependency on Clojure 1.6 and that it needs to be explicitly specified be documented in the README?
