### ISSUE TITLE
`lein cljsbuild once targetX targetY` leaks information between targets

### ISSUE THREAD

**Issue by dustingetz** [emezeske/lein-cljsbuild#385]
In the following snipped build output, src code from `dev-browser` ends up on the classpath for `dev-server` (see two bolded bits)

bash-3.2$ lein clean && lein cljsbuild once dev-browser dev-server
Compiling ClojureScript.
Compiling "resources/public/pp_web_browser.js" from ["client/src" "client/src_browser"]...
Mar 31, 2015 4:28:51 PM com.google.javascript.jscomp.LoggerErrorManager println
WARNING: file:/Users/dustingetz/.m2/repository/org/clojure/google-closure-library/0.0-20140718-946a7d39/google-closure-library-0.0-20140718-946a7d39.jar!/goog/net/jsonp.js:269: WARNING - Misplaced function annotation.
  return function(var_args) {
  ^

Mar 31, 2015 4:28:51 PM com.google.javascript.jscomp.LoggerErrorManager printSummary
WARNING: 0 error(s), 1 warning(s)
Successfully compiled "resources/public/pp_web_browser.js" in 20.665 seconds.
**Compiling "resources/public/pp_web_server.js" from ["client/src" "client/src_server"]...**
Compiling "resources/public/pp_web_server.js" failed.
clojure.lang.ExceptionInfo: failed compiling file:client/src/pp_web/anchor_click.cljs {:file #<File client/src/pp_web/anchor_click.cljs>}
	at clojure.core$ex_info.invoke(core.clj:4403)
	at cljs.compiler$compile_file$fn__3040.invoke(compiler.clj:1122)
	at clojure.main.main(main.java:37)
Caused by: clojure.lang.ExceptionInfo: No such namespace: history-js, could not locate 
history_js.cljs at line 1 
/Users/dustingetz/placepixel/placepixel-web-prototype/client/**src_browser**/pp_web/history_impl.cljs
 {:tag :cljs/analysis-error, :file "
/Users/dustingetz/placepixel/placepixel-web-prototype/client/src_browser/pp_web/history_impl.cljs
", :line 1, :column 1}
	at clojure.core$ex_info.invoke(core.clj:4403)
	at cljs.compiler$compile_file_STAR_.invoke(compiler.clj:970)
	at cljs.compiler$compile_file$fn__3040.invoke(compiler.clj:1107)
	... 47 more
Subprocess failed

**Comment by cemerick** [comment]
This is expected. You should probably use `lein do cljsbuild targetx, cljsbuild targety` if you want each build to have different classpaths, etc.
