### ISSUE TITLE
cljsbuild auto does not rebuild when .cljc file has changed

### ISSUE THREAD

**Issue by Skinney** [emezeske/lein-cljsbuild#389]
In Clojure 1.7 and the latest version of Clojurescript, shared code can reside in .cljc files. When building code with cljsbuild auto, changes in .cljc files does not trigger a rebuild.

**Comment by jarppe** [comment]
It would seem that it ignores .cljc files completely. If source paths have only .cljc files it does not compile at all.

**Comment by dmos62** [comment]
A dirty workaround is to save another file from the same cljsbuild profile that has a `.cljs` extension. Triggered compile includes the .cljc files.

**Comment by benfleis** [comment]
+1 on this :)

(I have looked at the code a little, and realize that unfortunately, submitting a patch to this is non-trivial for me. I will keep looking though.)

**Comment by cemerick** [comment]
Fixed on master, release coming soon.

**Comment by benfleis** [comment]
Fantastic! (Just looked at this earlier today, as I'm back at cljc work!)

**Comment by lprefontaine** [comment]
Hi, 

what's the best way to use master ? Any snapshot available ? Or should I build it locally ?
My brain is overheating. :) I have to think to save the .cljs file each time I do some mods.
I now have several folders only with .cljc files.

**Comment by lprefontaine** [comment]
I was wrong, I do have 1.0.6 and the fix is present in this version... I need to dig deeper.
Something is wrong here and it's most probably me.

**Comment by lprefontaine** [comment]
Ok, something corrupted but no idea exactly what. Whipped out everything by hand in the js folder.
Back to business...

**Comment by lprefontaine** [comment]
I think I found it. I had no explicit dependency on cljsbuild 1.0.6.
Just on the lein-cljsbuild plugin 1.0.6.

lein-figwheel 0.3.3 depends on 1.0.5.
Sometimes it worked at other times it did not.

I explicitly excluded cljsbuild in the figwheel dependency and added cljsbuild 1.0.6 explicitly.
Seems to be fine now.
