### ISSUE TITLE
generated xxxx-init.clj files in root

### ISSUE THREAD

**Issue by mhuebert** [emezeske/lein-cljsbuild#394]
I'm using figwheel and auto-building a CLJS app. Generated *-init.clj files (eg `0b21e194b30ecb571b267093ec0f129f5541677d-init.clj`) are showing up in my project root directory. Is this supposed to happen? Can I choose what directory they are saved in? My project.clj includes:

```clj
:cljsbuild {
    :builds [{:id "dev"
              :source-paths ["src"]
              :figwheel { :css-dirs ["resources/public/css"]
                         :http-server-root "public"}
              :compiler {:main client.core
                         :asset-path "cljs/out"
                         :output-to  "resources/public/cljs/main.js"
                         :output-dir "resources/public/cljs/out"} 
              }]
   }
```

**Comment by cemerick** [comment]
I think those files are supposed to be in /tmp, and are produced by cider (or some other part of that toolchain)? Maybe @bhauman knows?

**Comment by bhauman** [comment]
I think that they are created by lein when env variable LEIN_FAST_TRAMPOLINE is set.

**Comment by cemerick** [comment]
Yup, confirmed. Nothing we can do about them here.
