### ISSUE TITLE
1.0.6: Caused by: java.lang.RuntimeException: No such var: clojure.core/require-macros

### ISSUE THREAD

**Issue by benfleis** [emezeske/lein-cljsbuild#396]
In working on cljc code in https://github.com/tonsky/datascript I updated (excitedly!) to 1.0.6, and now get a stream of errors/stacktraces that always have 
```Caused by: java.lang.RuntimeException: No such var: clojure.core/require-macros```

I was working with CLJS 0.0-3211, but also tried 3269, same result.

The resulting code seems to work the same, but pages of ignorable exceptions make debugging real compiler errors much more difficult.

I will try to create a quick demo repo and link it here, although checking out the datascript lib, and doing 1.0.5 -> 1.0.6 is also sufficient.

EDIT: my full command line for producing this:
```
rm -rf target; lein do clean, cljsbuild test
```

**Comment by cemerick** [comment]
If you're talking about cljc code like [this](https://github.com/tonsky/datascript/blob/74b9e07c3deddd653baa60546bdc189ca8a5ea3e/test/datascript/test/query_v3.cljc#L2): that's failing because `:require-macros` isn't a valid `ns` clause in Clojure. You need to ensure that it's only visible to ClojureScript using reader conditionals.

**Comment by benfleis** [comment]
LOL. literally. sorry for the time waste... it's just been one days :)

**Comment by benfleis** [comment]
@cemerick If I might bother with one follow up -- why would the change from 1.0.5 -> 1.0.6 have caused this specifically? I was already compiling .cljc files w/ 1.0.5, so I had thus far been successful in only updating the `ns` expressions incrementally. (It's not yet expected that the clj builds/works.)
