### ISSUE TITLE
Documentation/sample inconsistency on builds

### ISSUE THREAD

**Issue by ricardojmendez** [emezeske/lein-cljsbuild#399]
[The comments for the sample project state](https://github.com/emezeske/lein-cljsbuild/blob/70a0d85782182a09c1116049b09a5f8ca5a7bd30/sample.project.clj#L62-L64):

```
    ; The :builds option should be set to a sequence of maps.  Each
    ; map will be treated as a separate, independent, ClojureScript
    ; compiler configuration.
```

However, all the examples use a map as the `:builds`, with that looks to be the build id for the key.  Both seem to work, but which one is the official approach? Will both be around for the foreseeable future?

**Comment by ricardojmendez** [comment]
As an aside, it seems like using the map approach, instead of the list of maps, is better when you need to override only some of these values for a profile.

**Comment by cemerick** [comment]
Interesting, I hadn't noticed that before. I wouldn't expect this to change.
