### ISSUE TITLE
cljsbuild compiler options defaults should match ClojureScript

### ISSUE THREAD

**Issue by swannodette** [emezeske/lein-cljsbuild#400]
Not doing so just creates cognitive dissonance and conflicting documentation. All the defaults presented in the ClojureScript Quick Start should be reflected in cljsbuild moving forward.

**Comment by cemerick** [comment]
I don't see any defaults presented in the quick start wiki per se, but I've eliminated the last of the defaults supplied by cljsbuild on the 1.x branch. Will be released as part of `1.1.0`.
