### ISSUE TITLE
advanced example test failed

### ISSUE THREAD

**Issue by kindlychung** [emezeske/lein-cljsbuild#401]
Here is the output in console:

    lein cljsbuild test unit
    Picked up _JAVA_OPTIONS: -Xms256m -Xmx2g
    Compiling ClojureScript.
    WARNING: lein-cljsbuild crossovers are deprecated, and will be removed in future versions. See https://github.com/emezeske/lein-cljsbuild/blob/master/doc/CROSSOVERS.md for details.
    Picked up _JAVA_OPTIONS: -Xms256m -Xmx2g
    Picked up _JAVA_OPTIONS: -Xms256m -Xmx2g
    Running ClojureScript test: unit
    Subprocess failed

**Comment by cemerick** [comment]
Sorry, I can't repro. Perhaps you don't have `phantomjs` installed?
