### ISSUE TITLE
Lein 2.5.2: WARNING: It appears your project does not contain a ClojureScript dependency.

### ISSUE THREAD

**Issue by arohner** [emezeske/lein-cljsbuild#402]
Not sure whether this is a lein issue, or a lein-cljsbuild issue.

lein-cljsbuild 1.0.6,
clojurescript 1.7.48

When upgrading from lein 2.5.1 to 2.5.2, I reliably see:

`WARNING: It appears your project does not contain a ClojureScript dependency. One will be provided for you by lein-cljsbuild, but it is strongly recommended that you add your own.  You can find a list of all ClojureScript releases here:
http://search.maven.org/#search|gav|1|g%3A%22org.clojure%22%20AND%20a%3A%22clojurescript%22`

Downgrading to lein 2.5.1 fixes the issue.

**Comment by nberger** [comment]
I can't reproduce the issue on the "simple" project from the "example-projects" directory. I did the following:

```
git clone https://github.com/emezeske/lein-cljsbuild.git
cd lein-cljsbuild
cd example-projects/simple 
sed -i "s/1.6.0/1.7.0/" project.clj    
sed -i "s/0.0-2411/1.7.48/" project.clj
lein version && lein cljsbuild once
```

Output is as follows:

``` 
Leiningen 2.5.2 on Java 1.7.0_55 OpenJDK 64-Bit Server VM
Compiling ClojureScript.
Retrieving compojure/compojure/1.1.6/compojure-1.1.6.pom from clojars
...
Compiling "resources/public/js/main.js" from ["src-cljs"]...
Successfully compiled "resources/public/js/main.js" in 12.853 seconds.
```

Please share your project.clj, or even better: a minimal reproducible project.

**Comment by arohner** [comment]
Hrm. I dug a little more, and `lein classpath` in 2.5.1 shows 371 jars, and the same command in 2.5.2 shows 14 jars, which all look like :plugins and :user things, and no project dependencies. Whatever that problem is, it seems very unlikely to be a lein-cljs issue. Sorry for the false alert.
