### ISSUE TITLE
Changing optimization should trigger recompilation

### ISSUE THREAD

**Issue by aengelberg** [emezeske/lein-cljsbuild#404]
If I stop a `lein cljsbuild auto`, change the optimization level in project.clj, then restart `lein cljsbuild auto`, it still waits until I change a line in my source file before recompiling.

**Comment by cemerick** [comment]
This is probably `wontfix` territory. Everything about cljsbuild uses mtimes right now to determine whether or not to kick off a compilation; keying off of `:cljsbuild` configuration would require persisting it separately after compilation completes, diffing it against the current config on startup, etc.

An alternative might be to _always_ compile once at startup, regardless of mtimes. If that's of interest, please open a separate issue and create a PR for it.
