### ISSUE TITLE
Eliminate cljs-compat

### ISSUE THREAD

**Issue by cemerick** [emezeske/lein-cljsbuild#406]
cljs-compat and its associated bits are a relic from a time when ClojureScript and its compiler "API" was churning rapidly, resulting in regular downstream breakage. The impression was that this was going to continue for some time, and so a mechanism was desired that would provide a way to fail a build fast rather than leave users with challenging errors. ClojureScript was distributed using an idiosyncratic versioning scheme, so things like Maven version ranges were not an option.

That breakage no longer occurs, and ClojureScript is growing a supported public API, so cljs-compat serves no purpose.

**Comment by cprice404** [comment]
Is there a blocker for this?  Or is it just a matter of someone filing a PR?  :)

**Comment by mneise** [comment]
No blocker so far, just a matter of me finishing it, but shouldn't be too far out :wink:

**Comment by cprice404** [comment]
Awesome, thanks, would be willing to volunteer to lend a hand if needed!

**Comment by mneise** [comment]
Thank you, help is always appreciated. I will probably go through the issues and add a label "PR welcome" to make it a bit easier for people.
