### ISSUE TITLE
cljs.test.async tests terminate the test suite

### ISSUE THREAD

**Issue by okal** [emezeske/lein-cljsbuild#411]
The example from [`cljs.test.async`](https://github.com/clojure/clojurescript/blob/be864bcb598b5e60f77f6629045bec5d80caf605/src/main/cljs/cljs/test.clj#L227) fails with an `(is true)` assert.

A minimal reproduction is available at https://github.com/okal/async-cljsbuild-failure-repro

**Comment by mneise** [comment]
@okal Thank you for providing a repo to reproduce this. I will look into this issue.

**Comment by okal** [comment]
Thank you. Let me know if I can be of further help.

**Comment by mneise** [comment]
The reason this fails is that phantomjs ignores timeouts (https://github.com/ariya/phantomjs/issues/10832). If you open `unit-test.html` in a browser after building the test should succeed.

**Comment by mneise** [comment]
The reason this fails is that phantomjs ignores timeouts (ariya/phantomjs#10832). If you open `unit-test.html` in a browser after running the build the test should succeed.
