### ISSUE TITLE
Could not find artifact lein-cljsbuild:lein-cljsbuild:jar:1.1.1-SNAPSHOT in clojars

### ISSUE THREAD

**Issue by tzach** [emezeske/lein-cljsbuild#424]
I'm getting
``Could not find artifact lein-cljsbuild:lein-cljsbuild:jar:1.1.1-SNAPSHOT in clojars (https://clojars.org/repo/)```

Using the following in project.clj
```
  :plugins [[lein-cljsbuild "1.1.1-SNAPSHOT"]]
```

**Comment by mneise** [comment]
Sorry, that was a mistake on my side. Updated the README too early. Try again with `1.1.0` instead ;)

**Comment by tzach** [comment]
Works! Thanks
