### ISSUE TITLE
Java Source Path

### ISSUE THREAD

**Issue by AshtonKem** [emezeske/lein-cljsbuild#434]
I have a mixed java/clj project that I'm trying to add lein-cljsbuild to. Unfortunately when trying to run `lein cljsbuild once` I get  ClassNotFoundExceptions due to the java sources included on java-source-path. I believe this is made worse by #362.

**Comment by mneise** [comment]
Could you please post your build configuration? Also, I assume you are trying to use lein-cljsbuild to build ClojureScript and not the java/clj part of your project?

**Comment by AshtonKem** [comment]
For some reason, I can no longer reproduce this problem. It must've been a version bug (I'm still scaffolding out the basics of cljs on this project), or some sequencing of timing bug I can't reproduce anymore. 

I guess close this bug, I'll report back here if I start seeing it again. 

--
Ashton

**Comment by AshtonKem** [comment]
Figured out how to recreate it, it had to do with running lein cljsbuild on its own, not via figwheel-sidecar as I'd switched to.

I've created a [sample repo](https://github.com/AshtonKem/cljsbuild-error-example) that demonstrates the problem.

**Comment by mneise** [comment]
Thank you for the repo. You are trying to use `lein-cljsbuild` for something that it was not built for, namely compiling Clojure. Instead, `lein-cljsbuild` is a plugin that uses the ClojureScript compiler to compile ClojureScript source files and not Clojure source files :wink:

**Comment by AshtonKem** [comment]
I don't think I was very clear, or my proposed solutions were just wrong.

The issue appears to be that lein-cljsbuild is attempting to process .clj files in a src directory that contains a mix of cljc, cljs, and clj files. This causes errors that are completely unrelated to the successful compilation of my cljs sources, but are still really annoying to the user. As far as I could tell, this could be fixed by:

* Either lein-cljsbuild or the cljs compiler ignoring .clj files
* Me separating my clj and cljs/cljc files into different directories.

The former seems better to me, as there is no real reason for cljs to touch clj files in my opinion. The latter I can implement myself, but strikes me as cumbersome.

**Comment by mneise** [comment]
@AshtonKem Yes, the convention is to put your ClojureScript and Clojure files in separate directories. The ClojureScript compiler actually also needs to process some .clj or .cljc files, since ClojureScript macros are written in Clojure :wink:

**Comment by AshtonKem** [comment]
I understand that it needs to process .cljc files, but I'm a bit
confused on why it process .clj files. Can any artifacts from clj file
compilation affect cljs/cljc output?

--
Ashton

"Maria Geller (Neise)" <notifications@github.com> writes:

> @AshtonKem Yes, the convention is to put your ClojureScript and Clojure files in
> separate directories. The ClojureScript compiler actually also needs to process
> some .clj or .cljc files, since ClojureScript macros are written in Clojure 
> :wink:
>
> —
> Reply to this email directly or view it on GitHub.
>
>

-- 
Ashton

**Comment by mneise** [comment]
Yes, as I said, ClojureScript macros are written in Clojure and therefore have to be in a .clj file.

**Comment by AshtonKem** [comment]
Well, that's unfortunate then. Guess there's nothing to be done.

-- 
Ashton

**Comment by w01fe** [comment]
I'm also running into this issue.  I've written a java Class that I would like to be able to access as part of ClojureScript compilation.

**Comment by mneise** [comment]
You only can use Java in your ClojureScript project when writing a macro, since macros in ClojureScript are written in Clojure.

**Comment by w01fe** [comment]
Thanks -- I'm aware of that, and that is the case I would like to support.  Specifically, I would like to use a Java class in the Clojure implementation of Schema, but currently this breaks the abilities to use schemas in macros that generate ClojureScript.

**Comment by mneise** [comment]
@AshtonKem I just had a look again at your example repo, and one way to make it work it to add `:source-paths ["src" "target/classes"]` to your project config and then run `lein do javac, cljsbuild once`.

I though that `javac` would run anyway before any plugin tasks are executed and that we wouldn't have to explicitly add `target/classes` to the classpath, so need to check why this is not the case.

@w01fe Maybe this workaround also helps in your case?

**Comment by w01fe** [comment]
@mneise Thanks -- I also just realized that this probably wouldn't have been an issue for users of schema (just the tests within the project), since the compiled Java class would be in the published jar and thus on the classpath for downstream users.  In any case, I ended up going a different route that didn't require a custom Java class.

**Comment by aiba** [comment]
I also have this issue.  A cljs file depends on a macro that depends on a java file in `:java-source-paths`.  Running `lein cljsbuild once` throws a `ClassNotFoundException`.

The workaround of adding `"target/classes"` to `:source-paths` is not helping me because my project specifies `:target-path "target/%s/"`.  So classes end up in `target/base+system+user+dev+cljs+b9e56754/classy-files`, and I'm not sure I should copy/paste that string into `project.clj`.

> I though that javac would run anyway before any plugin tasks are executed and that we wouldn't have to explicitly add target/classes to the classpath, so need to check why this is not the case.

It would be awesome if we could figure this out.

**Comment by mneise** [comment]
The reason for the mentioned `ClassNotFoundException` is that `lein javac` didn't run as a `prep-task` when running `lein cljsbuild`. I've fixed this in `1.1.7-SNAPSHOT` and will do a release soon.

**Comment by mneise** [comment]
Has been fixed with 0d085f9c868bbc6b90f786fd23569bf89c124dea.
