### ISSUE TITLE
Cljs-compat relies on Clojure 1.5.1

### ISSUE THREAD

**Issue by bhauman** [emezeske/lein-cljsbuild#435]
https://github.com/emezeske/lein-cljsbuild/blob/master/cljs-compat/project.clj#L12

very likely should be
[org.clojure/clojure "1.5.1" :scope "provided"]

**Comment by mneise** [comment]
Yeah, a lot of the dependencies are outdated. Luckily, cljs-compat will be removed in lein-cljsbuild 2.0 (#406).

**Comment by claj** [comment]
I also found this. Looking forward to lein-cljsbuild 2.0!

**Comment by mneise** [comment]
Just released `1.1.3` which removes `cljs-compat`.
