### ISSUE TITLE
:notify-command not being called?

### ISSUE THREAD

**Issue by danielcompton** [emezeske/lein-cljsbuild#437]
I've set up the `lein-cljsbuild/example-projects/simple` with 

```diff
               :compiler {:output-to "resources/public/js/main.js"
                          :optimizations :whitespace
+                         :notify-command ["say" "hi"]
                          :pretty-print true}}]}
```

I expect that on Mac OS X after running `lein cljsbuild once`, the notify command would be called and the system would say "Hi ...". However nothing seems to be happening. Am I using notify-command wrong, or is there a bug here?

**Comment by mneise** [comment]
You need to put the `:notify-command` option one level higher in your build options instead of putting them into the compiler options :wink:
