### ISSUE TITLE
Tools.reader dependency not respected

### ISSUE THREAD

**Issue by arichiardi** [emezeske/lein-cljsbuild#439]
Similarly to #270, today I have had a very similar problem with `1.1.2`. It looks like `tools.reader 1.0.0-alpha3` is never included in my compiled Javascript even if it is the only one appearing in `lein classpath`. Also `lein deps :tree` has only one dep and it is the right one.

I have a test against a specific version of `tools.reader` therefore I am sure that it is not included in my final `.js`. If somebody wants to play, this is available at https://github.com/Lambda-X/replumb/tree/tools-reader-bug (launching `lein test-phantom` should pass all the tests).

I tried my best to be really sure that this is not my mistake, but I apologise in advance if it will be.
My question would be, how can I debug what is the `cljs.build.api/build` command/classpath?

Thanks!

EDIT:
What I am expecting is, with profile `:none`, open `/out/cljs/tools/reader.cljs` and browse to line 705, it should be: https://github.com/clojure/tools.reader/blob/master/src/main/cljs/cljs/tools/reader.cljs#L705.

**Comment by danielcompton** [comment]
I'm not sure if this is your exact problem, but IIRC tools.reader was included in the Leiningen Uberjar at least until https://github.com/technomancy/leiningen/pull/2032. You wouldn't see this in your classpath, but it would show up ahead of your new dependency. What version of Leiningen are you running?

**Comment by arichiardi** [comment]
Version is: `Leiningen 2.6.0 on Java 1.8.0_72 Java HotSpot(TM) 64-Bit Server VM`

**Comment by arichiardi** [comment]
In my case an older version is used instead of the specified `1.0.0 alpha3`, so maybe a bit different problem. I have even tried to delete the old deps from the `.m2` but at least `0.9.2` and `0.8.4` (together with `1.0.0-alpha3`) are re-downloaded.

**Comment by arichiardi** [comment]
So @danielcompton I assume `cljsbuild` reads the dependencies from what `lein` collects right? Can you please give me a hint on where to look in the code?

**Comment by mneise** [comment]
The `project.clj` file in replumb seems to require `[org.clojure/tools.reader "1.0.0-alpha2"]`. Have you tried updating it to  `[org.clojure/tools.reader "1.0.0-alpha3"]`? From what I can tell `lein-cljsbuild` passes the correct dependency to leiningen when building the project and also the classpath looks good to me.

**Comment by arichiardi** [comment]
@mneise thanks for answering, it is in a branch actually: https://github.com/Lambda-X/replumb/tree/tools-reader-bug

**Comment by mneise** [comment]
@arichiardi I'm using the same version of lein-cljsbuild that's on your branch, so `1.1.1`, and `2.6.1` for Leiningen.

**Comment by arichiardi** [comment]
I will try `2.6.1`, and check if there has been some change that might solve this, thanks for checking it.

**Comment by arichiardi** [comment]
Just for curiosity, is `lein test-phantom` succeeding?

**Comment by arichiardi** [comment]
@danielcompton thanks for explaining that and no warnings at all, and there is only the right tools.reader in `lein :deps tree` because, as @hyPiRion explained on Slack, I have it in my main dependencies and close to the dep root (I even moved it in the very first position in my tests but no honey). I really wonder what I'd going on but as you said I will try with the latest version of `lein` where I think the problem lies.

**Comment by mneise** [comment]
No, it's not. With `[org.clojure/tools.reader "1.0.0-alpha3"]` I get 13 failures, whereas with `[org.clojure/tools.reader "1.0.0-alpha2"] only 2 failures.

**Comment by arichiardi** [comment]
Ok does not make sense any more now to me :dancers: In my PR there is one single failure, but I am on it. Thanks again a lot

**Comment by arichiardi** [comment]
Still not working...these are the versions dowloaded:

```
Retrieving org/clojure/tools.reader/0.9.2/tools.reader-0.9.2.pom from central
Retrieving org/clojure/tools.reader/0.10.0-alpha3/tools.reader-0.10.0-alpha3.pom from central
Retrieving org/clojure/tools.reader/0.9.1/tools.reader-0.9.1.pom from central
Retrieving org/clojure/tools.reader/0.10.0-alpha3/tools.reader-0.10.0-alpha3.jar from central
Retrieving org/clojure/tools.reader/1.0.0-alpha1/tools.reader-1.0.0-alpha1.pom from central
Retrieving org/clojure/tools.reader/1.0.0-alpha3/tools.reader-1.0.0-alpha3.pom from central
Retrieving org/clojure/tools.reader/0.8.4/tools.reader-0.8.4.pom from central
Retrieving org/clojure/tools.reader/0.8.10/tools.reader-0.8.10.pom from central
Retrieving org/clojure/tools.reader/1.0.0-alpha3/tools.reader-1.0.0-alpha3.jar from central
```

**Comment by arichiardi** [comment]
Again reporting, `lein uberjar` uses the right version, which finishes in the final `.jar`

**Comment by arichiardi** [comment]
What is the other difference between my and your environment @mneise? `profiles.clj`!
I commented mine and now I have 12 failures! So we found the problem!

This is the beginning, but again I could never have imagined that it could influence...

```
{:user
 {:plugins [[lein-kibit "0.1.2"]
            [com.jakemccrary/lein-test-refresh "0.12.0"]
            [refactor-nrepl "2.0.0-SNAPSHOT"]
            [cider/cider-nrepl "0.11.0-SNAPSHOT"]
            [lein-pprint "1.1.2"]
            #_[venantius/ultra "0.4.0"]]
  :dependencies [[org.clojure/tools.nrepl "0.2.12"]
                 [acyclic/squiggly-clojure "0.1.2-SNAPSHOT"]
                 [org.clojure/tools.namespace "0.2.11"]
                 [leiningen #=(leiningen.core.main/leiningen-version)]
                 #_[io.aviso/pretty "0.1.19"]
                 #_[spyscope "0.1.4"]
                 #_[alembic "0.3.2"]
                 #_[im.chit/vinyasa "0.4.2"]]
```

**Comment by mneise** [comment]
Do you know which version of `tool.reader` is used in your case instead of `1.0.0-alpha3`? Do you have any other local changes on your branch that you haven't committed yet? In my case (after deleting all local versions of `tools.reader`) the same versions that you've posted above are downloaded except for `0.8.4`.

**Comment by mneise** [comment]
The only thing that is in my `profiles.clj` is

```
{:repl {:plugins [[cider/cider-nrepl "0.10.2"]]}}
```

**Comment by arichiardi** [comment]
@mneise I do not know which version is used (how to know?), but without my profile up there, `1.0.0-alpha3` is taken, meaning that one of those deps are taking over, it would be interesting to know which one I agree, I have to think how to discover it.

**Comment by arichiardi** [comment]
Ah, no forgotten change

**Comment by arichiardi** [comment]
Commenting one by one my deps in `profile.clj` to see which is the offending one.

**Comment by arichiardi** [comment]
@mneise can you try to add `[refactor-nrepl "2.0.0-SNAPSHOT"]` and see if you get the same behavior?

**Comment by mneise** [comment]
@arichiardi Yes, adding `[refactor-nrepl "2.0.0-SNAPSHOT"]` to my `profiles.clj` gives me the same behavior, meaning `[org.clojure/tools.reader "1.0.0-alpha3"]` isn't used. So seems like it's no lein-cljsbuild problem after all :wink:

**Comment by arichiardi** [comment]
@mneise yes you are totally right, thanks for confirming this, I think I will move the problem to `lein`, where it belongs
