### ISSUE TITLE
goog.require("(quote hello.core)");

### ISSUE THREAD

**Issue by ngoffee** [emezeske/lein-cljsbuild#452]
When trying to compile a simple "Hello world!" executable for node.js, the output main.js contains a line that looks like an s-expression is being serialized where just a string is expected:

```
goog.require("(quote hello.core)");
```

Here's my project.clj:

```
(defproject hello-node-cljs "0.1.0-SNAPSHOT"
  :description "FIXME: write this!"
  :url "http://example.com/FIXME"

  :dependencies [[org.clojure/clojure "1.8.0"]
                 [org.clojure/clojurescript "1.9.227"]]

  :plugins [[lein-cljsbuild "1.1.4"]]

  :source-paths ["src" "target/classes"]
  :clean-targets ["out"]

  :cljsbuild {:builds [{:source-paths ["src"]
                        :compiler {:main 'hello.core
                                   :target :nodejs
                                   :output-to "out/main.js"
                                   :output-dir "out/main"
                                   :asset-path "out/main"
                                   :optimizations :none
                                   :pretty-print true
                                   :verbose true}}]})
```

And here's my src/hello/core.cljs:

```
(ns hello.core
  (:require [cljs.nodejs :as nodejs]))

(nodejs/enable-util-print!)

(defn -main [& args]
  (println "Hello world!"))

(set! *main-cli-fn* -main)
```

Compiling manually with the following build.clj instead of using lein-cljsbuild produces the correct output:

```
(require 'cljs.build.api)

(cljs.build.api/build "src"
  {:main 'hello.core
   :target :nodejs
   :output-to "out/main.js"
   :output-dir "out/main"
   :asset-path "out/main"
   :optimizations :none
   :pretty-print true
   :verbose true})
```

**Comment by danielcompton** [comment]
Leiningen already quotes symbols in `project.clj`, so you need to provide `hello.core` or `"hello.core"` in your `:main` build config, not `'hello.core`.

**Comment by ngoffee** [comment]
Thanks. It seems a little confusing that the syntax required is subtly different than what's required when using the compiler API by itself, but I'll close this.

**Comment by maksimr** [comment]
> Leiningen already quotes symbols in project.clj, so you need to provide hello.core or "hello.core" in your :main build config, not 'hello.core.

I totally agree with @ngoffee. This behavior is very confusing, especially for beginners.
