### ISSUE TITLE
Run shutdown-agents after a cljsbuild once if :notify-command is used

### ISSUE THREAD

**Issue by danielcompton** [emezeske/lein-cljsbuild#453]
`:notify-command` uses a `future` through `cljsbuild.util/process-start`. If a notify-command is run during a `cljsbuild once` run, then the cljsbuild process will stay running for another minute until the agents are shut down.

You can reproduce this on the Reagent project by running

```
$ lein with-profile prod-test do clean, cljsbuild once
```

**Comment by miikka** [comment]
`lein cljsbuild test` has the same problem, because the test commands are run with `cljsbuild.util/process-start` as well.
