### ISSUE TITLE
Audio notification

### ISSUE THREAD

**Issue by Cka3** [emezeske/lein-cljsbuild#462]
Hello and thanks for your hard work!

Is there a way to **add audio notification for successful/failed build?**  I would like to know if my build was successful or not without looking into console on every autobuil. 

Thanks

**Comment by emezeske** [comment]
There's a config option to run a command when the build succeeds/fails:

https://github.com/emezeske/lein-cljsbuild/blob/master/sample.project.clj#L78

Depending on your OS/etc you can run a command that plays a bell sound. (The example uses growlnotify for an OS notification.)
