### ISSUE TITLE
path building bug (WSL?)

### ISSUE THREAD

**Issue by Testare** [emezeske/lein-cljsbuild#464]
When using lein-cljsbuild on Bash on Ubuntu on Windows (The Windows Subsystem for Linux), running "lein cljsbuild once" seems to have a bug when "output-dir" is not specified, creating a file that requires an absolute path in the middle of an already absolute path making a garbage path. I don't know if this is specific to WSL, but I suspect it might be if it hasn't been reported as an obvious bug yet.

I've created a git repository to show-case the bug.

https://github.com/Testare/cljsbuild-wsl-bug

Currently simply specifying an output-dir will cause the code to work fine though, as far as I can tell.

**Comment by danielcompton** [comment]
Does this happen with Powershell or Batch?
