### ISSUE TITLE
data_readers.clj[c] should not be loaded

### ISSUE THREAD

**Issue by cemerick** [emezeske/lein-cljsbuild#466]
This is a regression of #360, via a84eb3e6a3da9cf3d1fefac73a192173c0d0973a.

In short, `data_readers.clj` and `data_readers.cljc` shouldn't ever be loaded by cljsbuild. If it is, it will always produce a build "error" in the log (e.g. `clojure.lang.Compiler$CompilerException: java.lang.RuntimeException: Unable to resolve symbol: inst in this context, compiling:(clj/data_readers.clj:1:197)`), though it appears to not affect the actual compilation outcome.

**Comment by mneise** [comment]
I wasn't able to reproduce this problem yet with the current `1.1.6` version. I've been using the [repo](https://github.com/tonsky/cljsbuild_data_readers) that has been provided to reproduce #360. If I understand correctly, `clojure.tools.namespace` won't load a clojure file if it [can't find a ns declaration](https://github.com/clojure/tools.namespace/blob/tools.namespace-0.2.11/src/main/clojure/clojure/tools/namespace/file.clj#L39).
Would be great if you could point me towards a repo that uses `1.1.6` and spits out the error mentioned above 😉

**Comment by cemerick** [comment]
Yeah, it turns out that an older cljsbuild version was getting sucked into the mix in that particular build. Very sorry for the bad report! 😬

**Comment by mneise** [comment]
No worries 😉 Thank you for double checking.
