### ISSUE TITLE
Readme links are broken (pointing to tag 1.1.7 which has not been pushed)

### ISSUE THREAD

**Issue by chr15m** [emezeske/lein-cljsbuild#470]
To replicate: 

 * Go to https://github.com/emezeske/lein-cljsbuild/
 * Click on "Launching ClojureScript tests"
 * Observe 404

**Comment by mneise** [comment]
Thank you for pointing this out 👍  Just fixed it.

**Comment by chr15m** [comment]
\o/ thank you (& also for clojurescript compiler contribs - much appreciated!) :+1:
