### ISSUE TITLE
How to use the preamble option?

### ISSUE THREAD

**Issue by mnn** [emezeske/lein-cljsbuild#472]
I am new to Clojure, Leiningen and ClojureScript, so it's very possible I am doing something basic wrong.

```clojure
(defproject xxx "0.1.0-SNAPSHOT"
  :dependencies [[org.clojure/clojure "1.8.0"]
                 [org.clojure/clojurescript "1.9.908"]]
  :plugins [[lein-cljsbuild "1.1.7"]]
  :hooks [leiningen.cljsbuild]
  :cljsbuild
  {:builds [{:source-paths ["src"]
             :compiler     {:output-to     "out/main.js"
                            :optimizations :advanced
                            :preamble      ["script_header.js"]}}]})

```

I have the preamble file in same directory as the `project.clj` is. I was expecting the file will be taken relative to this directory, but apparently it's not. I am getting:

```
WARNING: Preamble resource file not found: script_header.js
```

I also tried prefixing the path with `../`, moving file to source directory. How to modify the build file, so build thingy is able to locate the preamble file? (I only found something mentioning classpath, but I have no clue what that means in context of Leiningen/ClojureScript.)

**Comment by jszakmeister** [comment]
Try:

```clojure
(defproject xxx "0.1.0-SNAPSHOT"
  :dependencies [[org.clojure/clojure "1.8.0"]
                 [org.clojure/clojurescript "1.9.908"]]
  :plugins [[lein-cljsbuild "1.1.7"]]
  :hooks [leiningen.cljsbuild]

  ;; The script_header.js file needs to go in a resource folder...
  :resource-paths ["resources"]

  :cljsbuild
  {:builds [{:source-paths ["src"]
             :compiler     {:output-to     "out/main.js"
                            :optimizations :advanced
                            :preamble      ["script_header.js"]}}]})
```

And put `script_header.js` in a top-level `resources/` folder.

**Comment by mnn** [comment]
I am sorry for taking so long, your snippet is working nicely. Thank you very much :smiley:.
