### ISSUE TITLE
:preamble fails silently for missing preamble files

### ISSUE THREAD

**Issue by rbuchmann** [emezeske/lein-cljsbuild#476]
I am currently trying to use a preamble file, and noticed that it's possible to enter an incorrect filename there, or put the :preamble key outside of the compiler options, and cljsbuild will just silently ignore it.

I think there should be a warning for unknown keys in the configuration, as well as a warning if a preamble file could not be found.

**Comment by rbuchmann** [comment]
Correction: It should warn if the preamble setting is ignored because optimizations are :none
🤦‍♂️

**Comment by mneise** [comment]
As you already pointed out, ':preamble' is a ClojureScript compiler option, so you are welcome to create an issue there (https://dev.clojure.org/jira/browse/CLJS). Also, if you are interested in contributing to the compiler, this sounds like a good issue to start with 😉

**Comment by rbuchmann** [comment]
Hm, not the answer I was looking for, but quite reasonable. I remember watching a talk about this topic by someone with a name curiously similar to yours, maybe it's time to put into practice what I learned there :)
