### ISSUE TITLE
Sample lein project setup produces invalid regex error for me in chrome

### ISSUE THREAD

**Issue by mseddon** [emezeske/lein-cljsbuild#477]
It is *exactly* this issue, seen on 1.1.7, the bidi string is converted by closure from a hex escaped value back into raw utf-8, which is a bug upstream in closure compiler:

https://dev.clojure.org/jira/browse/CLJS-1547?focusedCommentId=42617&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-42617

Adding `:closure-output-charset "US-ASCII"` to the compiler options fixed it for me, perhaps it should be in the sample project, or perhaps lein-cljsbuild itself should quietly default to this setting?

**Comment by mneise** [comment]
I don't think lein-cljsbuild should default `:closure-output-charset` to `US-ASCII`, since this is a bug in the Closure compiler that should be fixed. Furthermore, `:closure-output-charset` is a ClojureScript compiler option and not a lein-cljsbuild option.
