### ISSUE TITLE
JS function scrambled .getTotalLength()

### ISSUE THREAD

**Issue by t-gebauer** [emezeske/lein-cljsbuild#480]
The advanced optimization scrambles the <path>.getTotalLength() function of SVG path elements. Resulting in
> TypeError: b.Zb is not a function (or something similar)

The project works fine without optimization: `lein figwheel`
But fails in production build: `lein do clean, cljsbuild once min`

Minimal example project setup (figwheel template)
[\<path\>  --- index.html](https://github.com/t-gebauer/cljsbuild-get-total-length/blob/25988ef2fd89e87b791980b92519425ade552cee/resources/public/index.html#L14)
[.getTotalLength() ---  core.cljs](https://github.com/t-gebauer/cljsbuild-get-total-length/blob/25988ef2fd89e87b791980b92519425ade552cee/src/cljs_get_total_length/core.cljs#L20-L21)

Is there a way to exclude certain keywords from the minifier? Or an other way to call that function so that it isn't changed?

**Comment by danielcompton** [comment]
Looks like the Closure compiler may not have externs for that function, you might want to raise it with them? You could provide your own extern in the meantime. In any case I don't think this is a cljsbuild issue?

**Comment by t-gebauer** [comment]
Yes you are right, seems like Closures fault. Though the extern is there...
https://github.com/google/closure-compiler/blob/b1a7b29686c9f3be2c137f1019f6d33ce1367f3d/contrib/externs/svg.js#L7383
