### ISSUE TITLE
:asset-path isn't documented

### ISSUE THREAD

**Issue by rnikander** [emezeske/lein-cljsbuild#484]
The docs say: "For an exhaustive list of the configuration options [...] see the sample.project.clj file." But the file doesn't document `:asset-path`, which I see it used in multiple places.  Eg, here: https://github.com/emezeske/lein-cljsbuild/wiki/Compilation-profiles

**Comment by danielcompton** [comment]
That line is talking about the options for the lein-cljsbuild plugin. :asset-path is a ClojureScript compiler configuration. You can see the details at https://clojurescript.org/reference/compiler-options. It could be good to update that line to point to that reference as well.
