### ISSUE TITLE
Possibility to add cli options to closure compiler.

### ISSUE THREAD

**Issue by nenadalm** [emezeske/lein-cljsbuild#487]
Hi. It would be useful to specify `--source_map_include_content` option.
(https://github.com/google/closure-compiler/issues/1890#issuecomment-282772095)

Reason is to see source in Sentry (logging service) https://forum.sentry.io/t/clojurescript-sourcemaps/257.

**Comment by danielcompton** [comment]
I think this is a ClojureScript compiler issue. See https://dev.clojure.org/jira/browse/CLJS-1755.

**Comment by nenadalm** [comment]
Thanks. I am closing the ticket then.
