### ISSUE TITLE
Exception (...)/objectutil.js is not a relative path

### ISSUE THREAD

**Issue by erno** [emezeske/lein-cljsbuild#490]
In https://github.com/finnishtransportagency/harja project we ran into a problem where developers on OS X (but not all) got an error like the following when starting cljsbuild/figwheel from leiningen, after a set of dependency updates (including clojurescript, fighweel, cljsbuild). I don't know if this the problem is specifically lein-cljsbuild, I picked this project as a guess.

Failed to compile "dev-resources/js/harja.js" in 74.202 seconds.
----  Exception    ----
  (some directory)/harja/dev-resources/js/out/l/objectutil.js is not a relative path

or in another instance just 

----  Exception    ----
  /dev-resources/js/out/l/objectutil.js is not a relative path

The problem persisted even after emptying ~/.m2 and making a fresh clone, but was went away when the source directory was moved to another place altogether.

I'm aware this is not a minimal or reliably reproducible bug report but felt it's good to record this somewhere publicly in case this rings a bell for someone, or if others run into the same thing.

**Comment by rauhala** [comment]
I experienced exactly same issue and was also able to recover by removing the repository and cloning again to different directory. Strange.

**Comment by mneise** [comment]
This sounds like an issue that is directly related to the ClojureScript compiler and not lein-cljsbuild, but it's very difficult to be sure without having a minimal repo to reproduce this problem.

@erno Do you still run into this problem or was this just a one-off? How did your `project.clj` look at that time? Which commands did you use?

**Comment by erno** [comment]
I was just reporting the issue on behalf of other teammembers who use OS X, and the affected people  applied the rename workaround after which the error didn't happen again.

The version of project.clj was this: https://github.com/finnishtransportagency/harja/blob/1b1760186b5bc8c128a297fef7d391542b0ec4ac/project.clj

I'm not personally on a Mac either.

I guess this is ok to close, if it's still Googlable if others run into the mystery.

**Comment by pragsmike** [comment]
I agree, this seems to have to do with the cljs compiler, but I'm adding this comment here as this issue
is what turns up when googling the error.

Renaming the top-level project directory "fixes" this problem for me.  Whether the error occurs seems to **depend on the length of the top-level directory name (!)**.  I'll continue to try working up a repro case, but it's a background task for me at the moment.  If anyone has any ideas where to look, let me know.

I'm using figwheel-main, and the specific error I get is
Caused by: java.lang.IllegalArgumentException: /public/cljs-out/dev/l/index.js is not a relative path

**Comment by kforner** [comment]
Definitely a bug relative to the parsing of the project directory. 

In a docker I mounted the same source code

- first in /app: lein clsbuild once failed with
```
java.lang.IllegalArgumentException: xxxx/highcharts.processor.js is not a relative path
```
- If I mount the same source code (acutally same directory) in /home/docker/project-dev instead if works just fine .

**Comment by shaminmeerankutty** [comment]
@erno Is this still not fixed?

**Comment by erno** [comment]
This bit me this time in another project in a CodeBuild pipeline. I tracked it down to here: https://github.com/clojure/clojurescript/blob/r1.10.520/src/main/clojure/cljs/closure.clj#L1851

In my case the lib-path didn't have any relevance to the path and the subs expression was just chopping it off at pretty random positions, sometimes unluckily just before a "/" sign. As a workaround I just put the source under a new fixed path in the CI config.

I'm leaving this here because I didn't manage to report it as a bug to in Clojurescript yet. (Following https://clojurescript.org/community/reporting-issues got mer as far as telling me my newly created Jira account doesn't have access to report bugs)

**Comment by erno** [comment]
This is being tracked as a compiler bug now here: https://clojure.atlassian.net/browse/CLJS-3241
