### ISSUE TITLE
Simple example project does not compile

### ISSUE THREAD

**Issue by achikin** [emezeske/lein-cljsbuild#498]
Steps to reproduce:
1. Clone the repo
2. cd example-projects/simple
3. lein cljsbuild once

Expected: Project builds successfully

Actual:
```
Could not find artifact lein-cljsbuild:lein-cljsbuild:jar:1.1.8-SNAPSHOT in clojars (https://repo.clojars.org/)
This could be due to a typo in :dependencies, file system permissions, or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
```
Changing lein-cljsbuild version to `1.1.7` fixes the issue.

**Comment by mneise** [comment]
Ah, thank you for catching this and also for the great issue report. Very appreciated!

Set it back to `1.1.7`.
