### ISSUE TITLE
cljsbuild-example-simple didnt run with lein 2.9.5 and Java version > 11 & 15

### ISSUE THREAD

**Issue by Mohanavadivel-git** [emezeske/lein-cljsbuild#500]
I m newbie tried to run the cljsbuild-example-simple, I didn't work like a charm, but i have to spend an hour to figure out the issue and it will be good that the examples to be mentioned with prerequisites:

Here is the problem i faced(in windows):

- Choclately install leiningen(2.9.5 got installed)
- I already had JDK 11
- Cloned repo lein-cljsbuild
- example projects didn't work with java11 and got below error:
      -  Exception in thread "main" java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter, compiling:(cljs/util.cljc:1:1)
- Then I downgraded my java version to java 8+lein 2.9.5 and got the below error
         - clojure.lang.Compiler$CompilerException: Syntax error macroexpanding clojure.core/fn at (clojure/core/unify.clj:83:18).
          #:clojure.error{:phase :macro-syntax-check, :line 83, :column 18, :source "clojure/core/unify.clj", :symbol clojure.core/fn}
- Finally I downgraded my lein to 2.8.3 (now the state is lein2.8.3+java8), It worked

Please check if this can be resolved, so that newbies are benefitted.

Thanks,
Mohan

**Comment by mneise** [comment]
Thank you for flagging this and for the detailed report. Much appreciated! I've [updated](https://github.com/emezeske/lein-cljsbuild/commit/089193c74e362c143d30dfca21a21e95c7ca112a) the advanced example project. Please let me know if you notice any further problems.
